version: "3.7"

services:
  caddy:
    container_name: humanbios-rasa
    image: humanbios-rasa
    restart: unless-stopped
    ports:
    - 5005:5005

networks:
  default:
    external:
      name: caddynet
