
# List of intents to generate nlu.md file
intents:
    # Values and their defaults, "*" means required
    # Values:               Default:
    #     folder*               -
    #     source                data.txt
    #     extract               -
    #     lookup                False
    #     prefixes              prefixes.csv
    #     suffixes              suffixes.csv
    #     use_prefixes          False
    #     use_suffixes          False
    #     sample_size %         45
    #     data_size %           100
    extract:
        - 
         folder:       language_detection
         extract:      language
         data_size:    45
         sample_size:  45
         lookup:       True
         use_prefixes: True
         use_suffixes: True
        - 
         folder:       country_detection
         extract:      country
         source:       data_country_names.csv
         data_size:    45
         sample_size:  45
         lookup:       True
         use_prefixes: True
         use_suffixes: True
        - 
         folder:       country_detection
         extract:      country_flag
         source:       data_country_flags.csv
         data_size:    45
         lookup:       True
    affirm:
        - 
         folder:     affirm
    deny:
        - 
         folder:     deny
    greet:
        - 
         folder:     greet

# Folders that contain files with synonyms
# 'folder_name: column_name'
synonyms:
    language_detection:    Language Name
    country_detection:     Country Name

# Will be appended without pre-processing
misc:
    - misc.csv
