
# List of intents to generate nlu.md file
intents:
    extract_lang_code:
         - 
           source:     language_codes.csv
           extract_as: language_code
         - 
           source:     language_names.csv
           extract_as: language_code
    extract_country:
         - 
           source:     country_names.csv
           extract_as: country_name

# Will be appended without pre-processing
misc:
    - misc.csv
    - synonyms_file.md
