
# List of intents to generate nlu.md file
intents:
    extract_lang_code:
         - 
           source:     flag_emoticons.csv
           extract_as: flag
         - 
           source:     language_codes.csv
           extract_as: language_code
    
    extract_lang_name:   
         - 
           source:     language_names.csv
           extract_as: language_name

misc:
    - misc.csv
